# Generated by Django 5.2.17 on 2026-09-24 23:45

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("immobilien", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="protokoll",
            name="anlagenblaetter_anzahl",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="protokoll",
            name="bestaetigt_am",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="protokoll",
            name="erste_miete_nachweis_vorhanden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="protokoll",
            name="heizungsablesungen",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="protokoll",
            name="kaution_nachweis_vorhanden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="protokoll",
            name="mieter_zukuenftige_anschrift",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="protokoll",
            name="nachbesserung_beschreibung",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="protokoll",
            name="nachbesserung_bis",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="protokoll",
            name="uebergabe_zeitpunkt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="protokoll",
            name="vermieter_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="protokoll",
            name="zaehlernummer_heizung",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="protokoll",
            name="zaehlernummer_strom",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="protokoll",
            name="zaehlernummer_wasser_kalt",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="protokoll",
            name="zaehlernummer_wasser_warm",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.CreateModel(
            name="ProtokollSchluessel",
            fields=[
                (
                    "protokoll_schluessel_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("anzahl", models.PositiveSmallIntegerField()),
                ("raum_bezeichnung", models.CharField(max_length=255)),
                ("aufschrift", models.CharField(blank=True, default="", max_length=255)),
                ("schluesselnummer", models.CharField(blank=True, default="", max_length=255)),
                ("fehlt", models.BooleanField(default=False)),
                ("fehlgrund", models.TextField(blank=True, default="")),
                ("nachlieferung_am", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "protokoll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protokoll_schluessel",
                        to="immobilien.protokoll",
                    ),
                ),
            ],
            options={
                "db_table": "protokoll_schluessel",
            },
        ),
    ]
