# Generated by Django 5.2.17 on 2026-09-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("immobilien", "0002_protokoll_anlagenblaetter_anzahl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="protokoll",
            name="bestaetigung_erklaert",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="protokoll",
            name="schluessel_ueberprueft",
            field=models.BooleanField(default=False),
        ),
    ]
