# Generated by Django 5.2.17 on 2026-09-25 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("immobilien", "0003_protokoll_bestaetigung_erklaert_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="wohnung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personen",
                to="immobilien.wohnung",
            ),
        ),
    ]
