# Generated by Django 5.2.17 on 2026-09-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("immobilien", "0004_person_wohnung"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protokoll",
            name="mieter_zukuenftige_anschrift",
            field=models.TextField(blank=True, default=""),
        ),
    ]
