# Generated by Django 5.2.17 on 2026-09-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("immobilien", "0005_alter_protokoll_mieter_zukuenftige_anschrift"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_employee",
            field=models.BooleanField(default=False),
        ),
    ]
