# Generated by Django 5.2.17 on 2026-09-28 13:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("immobilien", "0006_person_is_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtokollEntwurf",
            fields=[
                (
                    "protokoll_entwurf_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sitzungsschluessel", models.CharField(max_length=64)),
                ("entwurfsbereich", models.CharField(max_length=255)),
                ("daten", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "protokoll_entwurf",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sitzungsschluessel", "entwurfsbereich"),
                        name="protokoll_entwurf_eindeutig_pro_sitzung_und_bereich",
                    )
                ],
            },
        ),
    ]
