# Generated by Django 5.2.17 on 2026-09-29

from django.core.validators import MinValueValidator
from django.db import migrations, models


def normalize_existing_household_sizes(apps, schema_editor) -> None:
    Bewerbung = apps.get_model("immobilien", "Bewerbung")
    Bewerbung.objects.filter(personenanzahl__lt=1).update(personenanzahl=1)


class Migration(migrations.Migration):
    dependencies = [
        ("immobilien", "0007_protokollentwurf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bewerbung",
            name="personenanzahl",
            field=models.PositiveSmallIntegerField(default=1, validators=[MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name="bewerbung",
            name="ueber_mich",
            field=models.TextField(),
        ),
        migrations.RunPython(
            normalize_existing_household_sizes,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="bewerbung",
            constraint=models.CheckConstraint(
                condition=models.Q(("personenanzahl__gte", 1)),
                name="bewerbung_personenanzahl_mindestens_eins",
            ),
        ),
    ]
