# Generated by Django 5.2.17 on 2026-09-29 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("immobilien", "0008_merge_stellplatz_und_protokoll"),
        ("immobilien", "0009_person_user"),
    ]

    operations = []
