# Generated by Django 5.2.17 on 2026-09-30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("immobilien", "0009_raumstammdaten"),
        ("immobilien", "0010_merge_20260929_1146"),
    ]

    operations = []
