# Generated by Django 5.2.17 on 2026-09-30 13:25

import uuid

import django.db.models.deletion
from django.db import migrations, models

import wohnungsverwaltung.models


class Migration(migrations.Migration):
    dependencies = [
        ("immobilien", "0011_merge_rooms_and_applicants"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaumMerkmalFoto",
            fields=[
                (
                    "raum_merkmal_foto_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "datei",
                    models.ImageField(
                        upload_to=wohnungsverwaltung.models.handover_photo_upload_path
                    ),
                ),
                ("content_type", models.CharField(max_length=50)),
                ("dateigroesse", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "raum_merkmal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="immobilien.raummerkmal",
                    ),
                ),
            ],
            options={
                "db_table": "raum_merkmal_foto",
            },
        ),
    ]
