# Generated by Django 5.2.17 on 2026-10-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("immobilien", "0012_raummerkmalfoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="raummerkmalfoto",
            name="inhalt_hash_sha256",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="raummerkmalfoto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("inhalt_hash_sha256", ""), _negated=True),
                fields=("raum_merkmal", "inhalt_hash_sha256"),
                name="raum_merkmal_foto_hash_eindeutig",
            ),
        ),
    ]
