# Generated by Django 5.2.17 on 2026-09-30 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("immobilien", "0011_merge_rooms_and_applicants"),
        ("immobilien", "0013_employee_login_verification"),
    ]

    operations = []
