# Generated by Django 5.2.17 on 2026-10-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immobilien', '0013_raummerkmalfoto_inhalt_hash_sha256_and_more'),
        ('immobilien', '0015_loginipthrottle_accountloginthrottle'),
    ]

    operations = [
    ]
