# Generated by Django 5.2.17 on 2026-10-02 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("immobilien", "0016_merge_20261001_2020"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="protokoll",
            name="abgeschlossen_von",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="abgeschlossene_protokolle",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="protokoll",
            name="export_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="protokoll",
            name="gesichert_am",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="protokoll",
            name="mieter_unterschrift_fehlt_grund",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="protokoll",
            name="nachtraeglich_gesichert",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ProtokollUnterschrift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rolle",
                    models.CharField(
                        choices=[("mitarbeiter", "Mitarbeiter"), ("mieter", "Mieter")],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=511)),
                ("datei", models.TextField()),
                ("hash_sha256", models.CharField(max_length=64)),
                ("erfasst_am", models.DateTimeField()),
                (
                    "protokoll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unterschriften",
                        to="immobilien.protokoll",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("protokoll", "rolle"), name="unterschrift_pro_rolle"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rolle__in", ["mitarbeiter", "mieter"])),
                        name="unterschrift_gueltige_rolle",
                    ),
                ],
            },
        ),
    ]
