# Generated by Django 5.2.17 on 2026-10-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("immobilien", "0017_raummerkmal_eindeutig_pro_raumprotokoll"),
    ]

    operations = [
        migrations.AddField(
            model_name="bewerbung",
            name="main_application_unlocked",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Wird durch die Mitarbeiterseite nach Besichtigung und positiver "
                    "Eignungsentscheidung gesetzt."
                ),
            ),
        ),
        migrations.AddField(
            model_name="bewerbung",
            name="interest_withdrawn_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RemoveConstraint(
            model_name="bewerbung",
            name="bewerbung_eine_offene_pro_person",
        ),
        migrations.AddConstraint(
            model_name="bewerbung",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("interest_withdrawn_at__isnull", True),
                    ("status", "open"),
                ),
                fields=("person",),
                name="bewerbung_eine_offene_pro_person",
            ),
        ),
    ]
