# Generated by Django 5.2.17 on 2026-10-04 10:42

from django.db import migrations, models

import wohnungsverwaltung.models


class Migration(migrations.Migration):
    dependencies = [
        ("immobilien", "0018_main_application_access_and_withdrawal"),
    ]

    operations = [
        migrations.AddField(
            model_name="bewerbung",
            name="credit_report_proof",
            field=models.FileField(
                blank=True, upload_to=wohnungsverwaltung.models.credit_report_proof_upload_path
            ),
        ),
        migrations.AddField(
            model_name="bewerbung",
            name="identity_proof",
            field=models.FileField(
                blank=True, upload_to=wohnungsverwaltung.models.identity_proof_upload_path
            ),
        ),
        migrations.AddField(
            model_name="bewerbung",
            name="income_proof",
            field=models.FileField(
                blank=True, upload_to=wohnungsverwaltung.models.income_proof_upload_path
            ),
        ),
        migrations.AddField(
            model_name="bewerbung",
            name="submitted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
