# Generated by Django 5.2.17 on 2026-10-06 14:07

import uuid

import django.db.models.deletion
from django.db import migrations, models

import wohnungsverwaltung.models


class Migration(migrations.Migration):
    dependencies = [
        ("immobilien", "0019_merge_application_access_and_pdf"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApartmentPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=wohnungsverwaltung.models.apartment_photo_upload_path
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="immobilien.wohnung",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "pk"),
            },
        ),
    ]
