# Generated by Django 5.2.17 on 2026-10-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("immobilien", "0020_apartment_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="wohnung",
            name="description",
            field=models.TextField(blank=True, default="", max_length=5000),
        ),
        migrations.AddField(
            model_name="wohnung",
            name="energy_information",
            field=models.TextField(blank=True, default="", max_length=3000),
        ),
        migrations.AddField(
            model_name="wohnung",
            name="equipment",
            field=models.TextField(blank=True, default="", max_length=3000),
        ),
        migrations.AddField(
            model_name="wohnung",
            name="heating_type",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="wohnung",
            name="planned_move_in",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
