# Generated by Django 5.2.17 on 2026-10-04 14:46

import uuid

import django.db.models.deletion
from django.db import migrations, models

import wohnungsverwaltung.models


class Migration(migrations.Migration):
    dependencies = [
        ("immobilien", "0020_bewerbung_proof_original_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationProof",
            fields=[
                (
                    "proof_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("income", "Gehaltsnachweise"),
                            ("identity", "Identitätsnachweis"),
                            ("credit_report", "SCHUFA-Unterlage"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=wohnungsverwaltung.models.application_proof_upload_path
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proof_files",
                        to="immobilien.bewerbung",
                    ),
                ),
            ],
            options={
                "db_table": "application_proof",
                "ordering": ("uploaded_at", "proof_id"),
                "indexes": [
                    models.Index(fields=["application", "category"], name="app_proof_category_idx")
                ],
            },
        ),
    ]
