# Generated by Django 5.2.17 on 2026-10-06 13:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("immobilien", "0022_merge_main_and_application_proofs"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationProofCleanup",
            fields=[
                (
                    "cleanup_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("storage_name", models.CharField(max_length=512, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "application_proof_cleanup",
                "ordering": ("created_at", "cleanup_id"),
            },
        ),
    ]
