# Generated by Django 5.2.17 on 2026-10-07 07:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("immobilien", "0023_application_proof_cleanup_queue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bewerbung",
            name="review_priority",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Unbewertet"), (1, "Niedrig"), (2, "Normal"), (3, "Hoch")], default=0
            ),
        ),
        migrations.AddField(
            model_name="bewerbung",
            name="review_priority_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="wohnung",
            name="max_occupants",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wohnung",
            name="occupancy_requirement_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="wohnung",
            name="pet_review_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="wohnung",
            name="pet_review_required",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wohnung",
            name="requirements_version",
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.CreateModel(
            name="ApplicationReviewEvent",
            fields=[
                (
                    "review_event_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("priority_changed", "Priorität geändert"),
                            ("eligibility_approved", "Einzelfall freigegeben"),
                            ("main_unlocked", "Main-Bewerbung freigeschaltet"),
                            ("invitation_sent", "Einladung per E-Mail versendet"),
                            ("invitation_failed", "Einladungsversand fehlgeschlagen"),
                        ],
                        max_length=32,
                    ),
                ),
                ("from_value", models.CharField(blank=True, default="", max_length=32)),
                ("to_value", models.CharField(blank=True, default="", max_length=32)),
                ("reason", models.TextField(blank=True, default="")),
                ("requirements_version", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_review_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_events",
                        to="immobilien.bewerbung",
                    ),
                ),
            ],
            options={
                "db_table": "application_review_event",
                "ordering": ("-created_at", "-review_event_id"),
                "indexes": [
                    models.Index(
                        fields=["application", "kind", "requirements_version"],
                        name="review_app_kind_version_idx",
                    )
                ],
            },
        ),
    ]
