# Generated by Django 5.2.17 on 2026-10-09 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("immobilien", "0021_apartment_public_details"),
        ("immobilien", "0025_handover_archive_cleanup_queue"),
    ]

    operations = []
